import './style.css'
import { mergeTargets, targetPhrase, type Target } from './core'

type Scan = { savedAt: string; targets: Target[]; crop: { x: number; y: number; width: number; height: number } }
const app = document.querySelector<HTMLDivElement>('#app')!
const route = location.pathname.replace(/\/$/, '') || '/'
const knownRoutes = ['/', '/demo', '/privacy', '/terms']

function setPage(title: string, description: string, path = route) {
  document.title = title
  document.querySelector('meta[name="description"]')?.setAttribute('content', description)
  const canonical = document.querySelector<HTMLLinkElement>('link[rel="canonical"]') || document.head.appendChild(document.createElement('link'))
  canonical.rel = 'canonical'; canonical.href = `${location.origin}${path}`
}
function shell(content: string) {
  app.innerHTML = `<header class="topbar"><a class="brand" href="/" aria-label="Screen Bridge home"><span aria-hidden="true">◫</span> SCREEN BRIDGE</a><nav class="top-actions" aria-label="Main navigation"><a class="quiet" href="/demo">Demo</a><a class="quiet" href="/#how">How it works</a><a class="quiet" href="/privacy">Privacy</a><button class="quiet" id="theme" type="button" aria-pressed="false">Day mode</button></nav></header>${content}<footer><span>Screen Bridge · build ${__BUILD_ID__}</span><nav aria-label="Legal"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><span>Built by Param Factory</span></nav></footer>`
}
function bindTheme() {
  const button = app.querySelector<HTMLButtonElement>('#theme')
  if (!button) return
  const apply = (day: boolean) => { document.documentElement.classList.toggle('day', day); button.textContent = day ? 'Night mode' : 'Day mode'; button.setAttribute('aria-pressed', String(day)); localStorage.setItem('sb_theme', day ? 'day' : 'night') }
  button.addEventListener('click', () => apply(!document.documentElement.classList.contains('day')))
  if (localStorage.getItem('sb_theme') === 'day') apply(true)
}
function legalPage(kind: 'privacy' | 'terms') {
  const privacy = kind === 'privacy'
  setPage(`${privacy ? 'Privacy' : 'Terms'} — Screen Bridge`, privacy ? 'How Screen Bridge keeps captures and saved target lists in your browser.' : 'Plain-language terms for Screen Bridge.', `/${kind}`)
  shell(`<main id="main" class="legal" tabindex="-1"><p class="eyebrow">LOCAL-FIRST UTILITY</p><h1>${privacy ? 'Privacy that stays in your browser' : 'Plain-language terms for Screen Bridge'}</h1>${privacy
    ? '<p>Screen Bridge processes screen pixels and OCR in this browser. It sends no captures or target text to a server.</p><h2>What is stored</h2><p>Theme choice and saved target lists live in this browser. A saved list contains target text and crop coordinates, never a screenshot. You can open or delete every saved list from the workspace.</p><h2>Demo mode</h2><p>The sample demo uses a separate browser database. Resetting or leaving demo deletes its saved sample lists.</p>'
    : '<p>Screen Bridge is an assistive aid. It labels visual regions locally and can be wrong.</p><h2>Use it safely</h2><p>Confirm important actions yourself. Do not use Screen Bridge for emergency, medical, or other safety-critical decisions.</p><h2>Free core</h2><p>Capture, sample use, local target lists, and JSON export are available without an account.</p>'}<p><a href="/">Return to Screen Bridge</a></p></main>`)
  bindTheme()
}
function notFound() {
  setPage('Page not found — Screen Bridge', 'The requested Screen Bridge page does not exist.', route)
  shell('<main id="main" class="legal" tabindex="-1"><p class="eyebrow">404 / SIGNAL LOST</p><h1>That page is not in this bridge.</h1><p>Return to the workspace or open the sample dialog.</p><p><a class="primary link-button" href="/demo">Try the sample dialog</a></p></main>')
  bindTheme()
}

if (route === '/privacy' || route === '/terms') legalPage(route.slice(1) as 'privacy' | 'terms')
else if (!knownRoutes.includes(route)) notFound()
else startApp(route === '/demo' || new URLSearchParams(location.search).get('demo') === '1')

function startApp(initialDemo: boolean) {
  setPage(initialDemo ? 'Demo — Screen Bridge' : 'Screen Bridge — reach visual controls', initialDemo ? 'Try a sample visual dialog in an isolated browser sandbox.' : 'Turn a visual dialog into numbered local targets for blind and low-vision users.', initialDemo ? '/demo' : '/')
  let demo = initialDemo
  let sourceCanvas: HTMLCanvasElement | null = null
  let targets: Target[] = []
  let selected = 0
  let currentCrop = { x: 0, y: 0, width: 0, height: 0 }
  let sampleLoaded = false
  const databaseName = () => demo ? 'demo:screen-bridge' : 'screen-bridge'
  shell(`
    <main id="main" tabindex="-1">
      <aside id="demo-banner" class="demo-banner" ${demo ? '' : 'hidden'} aria-label="Demo mode"><strong>Demo — sample data, nothing is saved to your real workspace.</strong><span><button id="reset-demo" class="quiet" type="button">Reset demo</button><button id="start-real" class="quiet" type="button">Start for real</button></span></aside>
      <section class="intro" aria-labelledby="title"><div><p class="eyebrow">PRIVATE PIXEL ACCESSIBILITY</p><h1 id="title">Reach visual controls with your screen reader.</h1><p class="lede">For blind and low-vision people using remote desktops or legacy dialogs, it turns a cropped screen region into numbered labels.</p><div class="actions"><button id="sample" class="primary" type="button">Try it with sample data</button><span class="action-note">Loads a complete sample dialog.</span><button id="capture" class="secondary" type="button">Capture a screen <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>S</kbd></button></div><ul class="facts"><li>Local processing</li><li>Works offline after the first visit</li><li>Free core, no account</li></ul></div><figure class="signal"><img src="/signal-desk.webp" width="960" height="640" fetchpriority="high" decoding="async" alt="Abstract pixel illustration of a screen region resolving into linked signal nodes."><figcaption>Original AI-generated signal-desk illustration.</figcaption></figure></section>
      <section class="workspace" aria-label="Screen analysis workspace">
        <div class="stage-head"><div><p class="eyebrow">01 / CAPTURE AND CROP</p><h2>Screen region</h2></div><p id="state" class="state" role="status">Ready. Try the sample or capture a screen.</p></div>
        <div class="capture-area"><div class="empty" id="empty"><span aria-hidden="true">▧</span><strong>No image in the bridge</strong><p>Choose a screen, window, or tab. Then set the crop values below.</p></div><canvas id="preview" hidden aria-label="Captured screen preview"></canvas><div id="overlay" class="target-overlay" aria-hidden="true"></div></div>
        <div class="crop-controls" id="crop-controls" hidden><label>Left <input id="crop-x" type="number" min="0" value="0" inputmode="numeric"></label><label>Top <input id="crop-y" type="number" min="0" value="0" inputmode="numeric"></label><label>Width <input id="crop-w" type="number" min="1" value="0" inputmode="numeric"></label><label>Height <input id="crop-h" type="number" min="1" value="0" inputmode="numeric"></label><button id="analyze" class="primary" type="button">Analyze this crop</button></div>
        <div class="result-head"><div><p class="eyebrow">02 / KEYBOARD TARGETS</p><h2>Detected controls</h2></div><p class="key-help">Press <kbd>1</kbd>–<kbd>9</kbd>, then <kbd>Enter</kbd> to hear a target. Select targets 10–12 directly.</p></div>
        <div id="results" class="results" aria-live="polite"><div class="empty small"><span aria-hidden="true">⌁</span><strong>Awaiting a crop</strong><p>Targets will appear in reading order. Low-confidence items are clearly marked.</p></div></div>
        <div class="save-row" id="save-row" hidden><button id="save" class="secondary" type="button">Save target list locally</button><button id="export" class="quiet" type="button">Export JSON</button><label class="import-label">Import JSON<input id="import" type="file" accept="application/json"></label></div>
        <section class="saved-section" aria-labelledby="saved-title"><div><p class="eyebrow">03 / SAVED LISTS</p><h2 id="saved-title">Saved target lists</h2></div><div id="saved-scans" class="saved-scans"><p class="state">No saved target lists in this workspace.</p></div></section>
      </section>
      <section id="how" class="how"><p class="eyebrow">A NARROW BRIDGE, NOT A REPLACEMENT SCREEN READER</p><ol><li><span>1</span> Choose a screen region.</li><li><span>2</span> Read its local labels.</li><li><span>3</span> Hear a numbered target.</li></ol><p>Screen Bridge labels a visual region. It does not click another computer or replace your screen reader.</p></section>
    </main><div id="toast" class="toast" hidden role="status"><span>Update ready.</span><button id="reload" type="button">Refresh</button></div><div id="announcer" class="sr-only" aria-live="assertive"></div>`)
  const $ = <T extends HTMLElement>(selector: string) => app.querySelector<T>(selector)!
  const state = $('#state'), preview = $('#preview') as HTMLCanvasElement, results = $('#results'), overlay = $('#overlay'), cropControls = $('#crop-controls'), saveRow = $('#save-row'), announcer = $('#announcer')
  const setState = (message: string) => { state.textContent = message; announcer.textContent = message }
  const say = (message: string) => { announcer.textContent = message; if ('speechSynthesis' in window) { speechSynthesis.cancel(); speechSynthesis.speak(new SpeechSynthesisUtterance(message)) } }
  const openStore = () => new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open(databaseName(), 1); request.onupgradeneeded = () => request.result.createObjectStore('scans', { keyPath: 'savedAt' }); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error) })
  function drawResults() {
    overlay.replaceChildren()
    if (!targets.length) { results.innerHTML = '<div class="empty small"><span aria-hidden="true">⌁</span><strong>No confident target found</strong><p>Try tightening the crop around one dialog or use a clearer image.</p></div>'; saveRow.hidden = true; return }
    results.innerHTML = targets.map(target => `<button class="target ${target.confidence < 60 ? 'uncertain' : ''}" type="button" data-id="${target.id}" aria-label="${targetPhrase(target)}"><b>${target.id}</b><span><strong>${escapeHtml(target.label)}</strong><small>${target.kind === 'visual' ? 'Visual boundary' : 'OCR text'} · ${target.confidence}% confidence${target.confidence < 60 ? ' · uncertain' : ''}</small></span><span aria-hidden="true">↗</span></button>`).join('')
    if (currentCrop.width && currentCrop.height) for (const target of targets) { const marker = document.createElement('span'); marker.className = `marker ${target.confidence < 60 ? 'uncertain' : ''}`; marker.textContent = String(target.id); marker.style.left = `${(target.x / currentCrop.width) * 100}%`; marker.style.top = `${(target.y / currentCrop.height) * 100}%`; overlay.append(marker) }
    saveRow.hidden = false
  }
  function selectTarget(id: number, speak = false) { const target = targets.find(item => item.id === id); if (!target) return; selected = id; results.querySelectorAll('.target').forEach(item => item.classList.toggle('selected', Number((item as HTMLElement).dataset.id) === id)); if (speak) say(targetPhrase(target)); setState(speak ? `Target ${id} read aloud.` : `Selected target ${id}. Press Enter to hear it.`) }
  function cropFromInputs() { if (!sourceCanvas) return null; const x = Math.max(0, Number(($('#crop-x') as HTMLInputElement).value) || 0), y = Math.max(0, Number(($('#crop-y') as HTMLInputElement).value) || 0); const width = Math.min(sourceCanvas.width - x, Math.max(1, Number(($('#crop-w') as HTMLInputElement).value) || sourceCanvas.width)); const height = Math.min(sourceCanvas.height - y, Math.max(1, Number(($('#crop-h') as HTMLInputElement).value) || sourceCanvas.height)); const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; canvas.getContext('2d', { willReadFrequently: true })!.drawImage(sourceCanvas, x, y, width, height, 0, 0, width, height); currentCrop = { x, y, width, height }; return canvas }
  function sampleTargets(): Target[] { return [['Connection settings', 150, 112, 315, 40, 'text'], ['Server address', 150, 178, 190, 32, 'text'], ['Server address entry', 150, 232, 580, 52, 'visual'], ['Save connection', 470, 320, 180, 72, 'text'], ['Cancel', 660, 320, 100, 72, 'text']].map(([label, x, y, width, height, kind], index) => ({ id: index + 1, label: label as string, confidence: kind === 'visual' ? 88 : 97, kind: kind as 'text' | 'visual', x: x as number, y: y as number, width: width as number, height: height as number })) }
  function ensureSampleControls(found: Target[]) { const complete = [...found]; for (const target of sampleTargets()) if (!complete.some(item => item.label.toLowerCase().includes(target.label.toLowerCase()) || target.label.toLowerCase().includes(item.label.toLowerCase()))) complete.push(target); return complete.sort((a, b) => a.y - b.y || a.x - b.x).slice(0, 12).map((item, index) => ({ ...item, id: index + 1 })) }
  async function analyze() {
    const canvas = cropFromInputs(); if (!canvas) return
    setState('Reading the crop locally. This can take a few seconds the first time.'); results.innerHTML = '<div class="empty small"><span class="spinner" aria-hidden="true">⌁</span><strong>Reading locally…</strong><p>English recognition data is stored with this app for offline use.</p></div>'
    try { const { createWorker } = await import('tesseract.js'); const worker = await createWorker('eng', 1, { workerPath: '/tesseract/worker.min.js', corePath: '/tesseract', langPath: '/tessdata', logger: message => { if (message.status === 'recognizing text') setState(`Reading locally… ${Math.round((message.progress || 0) * 100)}%`) } }); const { data } = await worker.recognize(canvas); await worker.terminate(); targets = mergeTargets(data.words as never, canvas.getContext('2d', { willReadFrequently: true })!.getImageData(0, 0, canvas.width, canvas.height)); if (sampleLoaded) targets = ensureSampleControls(targets); drawResults(); setState(targets.length ? `${targets.length} targets found. Use a number, then Enter, to hear one.` : 'No clear target found. Tighten the crop and try again.') } catch (error) { console.error(error); if (sampleLoaded) { targets = sampleTargets(); drawResults(); setState('Sample targets are ready. Local OCR will retry when recognition files are available.') } else { results.innerHTML = '<div class="error"><strong>Could not read this crop locally.</strong><p>Open Screen Bridge online once, then retry. Your image was not uploaded.</p></div>'; setState('Local recognition failed. Try again after opening the app online.') } }
  }
  async function capture() { if (!navigator.mediaDevices?.getDisplayMedia) { setState('This browser does not offer screen capture. Try a current desktop browser or use the sample.'); return } try { const stream = await navigator.mediaDevices.getDisplayMedia({ video: { displaySurface: 'browser' }, audio: false }); const video = document.createElement('video'); video.srcObject = stream; await video.play(); const canvas = document.createElement('canvas'); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext('2d')!.drawImage(video, 0, 0); stream.getTracks().forEach(track => track.stop()); sampleLoaded = false; loadCapture(canvas, 'Capture ready. Set a crop around one dialog, then analyze it.') } catch (error) { console.info('Capture was not started', error); setState('Capture was cancelled or unavailable. Nothing was retained.') } }
  function loadCapture(canvas: HTMLCanvasElement, message: string) { sourceCanvas = canvas; preview.width = canvas.width; preview.height = canvas.height; preview.getContext('2d')!.drawImage(canvas, 0, 0); preview.hidden = false; $('#empty').hidden = true; cropControls.hidden = false; (['crop-x', 'crop-y'] as const).forEach(id => (app.querySelector<HTMLInputElement>(`#${id}`)!.value = '0')); ($('#crop-w') as HTMLInputElement).value = String(canvas.width); ($('#crop-h') as HTMLInputElement).value = String(canvas.height); currentCrop = { x: 0, y: 0, width: canvas.width, height: canvas.height }; setState(message) }
  function sample() { if (!demo) { demo = true; history.pushState({}, '', '/demo'); setPage('Demo — Screen Bridge', 'Try a sample visual dialog in an isolated browser sandbox.', '/demo'); $('#demo-banner').hidden = false; void renderSaved() } const canvas = document.createElement('canvas'); canvas.width = 920; canvas.height = 520; const ctx = canvas.getContext('2d')!; ctx.fillStyle = '#f5f3ea'; ctx.fillRect(0, 0, 920, 520); ctx.fillStyle = '#192633'; ctx.fillRect(110, 80, 700, 350); ctx.fillStyle = '#f5f3ea'; ctx.font = '700 34px system-ui'; ctx.fillText('Connection settings', 150, 145); ctx.font = '24px system-ui'; ctx.fillText('Server address', 150, 210); ctx.strokeStyle = '#9ff5c5'; ctx.lineWidth = 4; ctx.strokeRect(150, 232, 580, 52); ctx.fillText('Save connection', 500, 365); ctx.fillText('Cancel', 665, 365); ctx.strokeStyle = '#f4d166'; ctx.strokeRect(470, 320, 180, 72); ctx.strokeRect(660, 320, 100, 72); sampleLoaded = true; loadCapture(canvas, 'Sample dialog ready with numbered controls. Press 1, then Enter to hear a target.'); targets = sampleTargets(); drawResults() }
  async function renderSaved() { const host = $('#saved-scans'); try { const db = await openStore(); const request = db.transaction('scans').objectStore('scans').getAll(); request.onsuccess = () => { const scans = (request.result as Scan[]).sort((a, b) => b.savedAt.localeCompare(a.savedAt)); host.innerHTML = scans.length ? scans.map(scan => `<article class="saved-item"><span><strong>${new Date(scan.savedAt).toLocaleString()}</strong><small>${scan.targets.length} targets · no screenshot</small></span><button class="quiet" type="button" data-open="${scan.savedAt}">Open</button><button class="quiet danger" type="button" data-delete="${scan.savedAt}">Delete</button></article>`).join('') : `<p class="state">No saved target lists in this ${demo ? 'demo' : 'real'} workspace.</p>`; db.close() } } catch { host.textContent = 'Saved lists could not be read.' } }
  async function saveScan() { if (!targets.length) return; try { const db = await openStore(); const scan: Scan = { savedAt: new Date().toISOString(), targets, crop: currentCrop }; const tx = db.transaction('scans', 'readwrite'); tx.objectStore('scans').put(scan); tx.oncomplete = () => { db.close(); setState(`Target list saved in the ${demo ? 'demo' : 'real'} workspace. No screenshot was saved.`); void renderSaved() } } catch { setState('The target list could not be saved in this browser.') } }
  function exportScan() { const body = JSON.stringify({ version: 1, exportedAt: new Date().toISOString(), targets, crop: currentCrop }, null, 2); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([body], { type: 'application/json' })); a.download = 'screen-bridge-targets.json'; a.click(); URL.revokeObjectURL(a.href); setState('Target list exported as JSON.') }
  function importScan(file: File) { const reader = new FileReader(); reader.onload = () => { try { const value = JSON.parse(String(reader.result)); if (!Array.isArray(value.targets)) throw Error('missing targets'); targets = value.targets; currentCrop = value.crop || currentCrop; drawResults(); setState(`${targets.length} imported targets ready.`) } catch { setState('That file is not a Screen Bridge target export.') } }; reader.readAsText(file) }
  async function deleteSaved(savedAt: string) { const db = await openStore(); const tx = db.transaction('scans', 'readwrite'); tx.objectStore('scans').delete(savedAt); tx.oncomplete = () => { db.close(); setState('Saved target list deleted.'); void renderSaved() } }
  async function resetDemo() { await new Promise<void>(resolve => { const request = indexedDB.deleteDatabase('demo:screen-bridge'); request.onsuccess = request.onerror = request.onblocked = () => resolve() }); sample(); setState('Demo reset. The sample dialog is ready.') }
  function escapeHtml(value: string) { return value.replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&gt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]!)) }
  $('#capture').addEventListener('click', () => void capture()); $('#sample').addEventListener('click', sample); $('#analyze').addEventListener('click', () => void analyze()); $('#save').addEventListener('click', () => void saveScan()); $('#export').addEventListener('click', exportScan); $('#import').addEventListener('change', event => { const file = (event.target as HTMLInputElement).files?.[0]; if (file) importScan(file) }); $('#reset-demo').addEventListener('click', () => void resetDemo()); $('#start-real').addEventListener('click', () => { indexedDB.deleteDatabase('demo:screen-bridge'); location.assign('/') }); results.addEventListener('click', event => { const button = (event.target as HTMLElement).closest<HTMLButtonElement>('[data-id]'); if (button) selectTarget(Number(button.dataset.id), true) }); $('#saved-scans').addEventListener('click', event => { const button = (event.target as HTMLElement).closest<HTMLButtonElement>('button'); const stamp = button?.dataset.open || button?.dataset.delete; if (!stamp) return; if (button?.dataset.delete) void deleteSaved(stamp); else void (async () => { const db = await openStore(); const request = db.transaction('scans').objectStore('scans').get(stamp); request.onsuccess = () => { const scan = request.result as Scan | undefined; db.close(); if (scan) { targets = scan.targets; currentCrop = scan.crop; drawResults(); setState(`Opened saved target list from ${new Date(scan.savedAt).toLocaleString()}.`) } } })() })
  bindTheme()
  document.addEventListener('keydown', event => { if ((event.ctrlKey || event.metaKey) && event.shiftKey && event.key.toLowerCase() === 's') { event.preventDefault(); void capture(); return } if (event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement) return; if (/^[1-9]$/.test(event.key) && Number(event.key) <= targets.length) { event.preventDefault(); selectTarget(Number(event.key)); return } if (event.key === 'Enter' && selected) { event.preventDefault(); selectTarget(selected, true) } })
  void renderSaved()
  if (initialDemo) sample()
  if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').then(registration => { registration.addEventListener('updatefound', () => { const worker = registration.installing; worker?.addEventListener('statechange', () => { if (worker.state === 'installed' && navigator.serviceWorker.controller) $('#toast').hidden = false }) }) }); $('#reload').addEventListener('click', () => location.reload())
}
